-- ============================================================
-- V1 — Schema base (5 tabelas originais)
-- Prefixo yp_t_ nas tabelas; constraints e índices sem prefixo.
-- Identidade BY DEFAULT para permitir ids explícitos no seed (V4).
-- ============================================================

CREATE TABLE yp_t_responsaveis (
                                   id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nome      VARCHAR2(100) NOT NULL,
                                   email     VARCHAR2(150) NOT NULL,
                                   telefone  VARCHAR2(20),
                                   CONSTRAINT uk_responsavel_email UNIQUE (email)
);

CREATE TABLE yp_t_veterinarios (
                                   id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nome           VARCHAR2(100) NOT NULL,
                                   email          VARCHAR2(150) NOT NULL,
                                   telefone       VARCHAR2(20),
                                   crmv           VARCHAR2(20)  NOT NULL,
                                   especialidade  VARCHAR2(100),
                                   CONSTRAINT uk_veterinario_email UNIQUE (email),
                                   CONSTRAINT uk_veterinario_crmv  UNIQUE (crmv)
);

CREATE TABLE yp_t_pets (
                           id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           responsavel_id  NUMBER(19)    NOT NULL,
                           nome            VARCHAR2(100) NOT NULL,
                           raca            VARCHAR2(100),
                           idade           NUMBER(10),
                           peso            NUMBER(5,2),
                           sexo_pet            VARCHAR2(20)  NOT NULL,
                           CONSTRAINT fk_pet_responsavel
                               FOREIGN KEY (responsavel_id) REFERENCES yp_t_responsaveis(id),
                           CONSTRAINT ck_pet_sexo  CHECK (sexo_pet IN ('MACHO','FEMEA')),
                           CONSTRAINT ck_pet_idade CHECK (idade BETWEEN 0 AND 30)
);

CREATE TABLE yp_t_consultas (
                                id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                pet_id          NUMBER(19)     NOT NULL,
                                veterinario_id  NUMBER(19)     NOT NULL,
                                tipo            VARCHAR2(20)   NOT NULL,
                                descricao       VARCHAR2(1000),
                                data            TIMESTAMP      NOT NULL,
                                observacoes     VARCHAR2(1000),
                                status          VARCHAR2(20)   NOT NULL,
                                CONSTRAINT fk_consulta_pet
                                    FOREIGN KEY (pet_id) REFERENCES yp_t_pets(id),
                                CONSTRAINT fk_consulta_veterinario
                                    FOREIGN KEY (veterinario_id) REFERENCES yp_t_veterinarios(id),
                                CONSTRAINT ck_consulta_status
                                    CHECK (status IN ('AGENDADA','REALIZADA','CANCELADA')),
                                CONSTRAINT ck_consulta_tipo
                                    CHECK (tipo IN ('ROTINA','VACINACAO','EMERGENCIA','RETORNO','EXAME'))
);

CREATE TABLE yp_t_historico_clinico (
                                        id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        pet_id     NUMBER(19)   NOT NULL,
                                        tipo       VARCHAR2(20) NOT NULL,
                                        descricao  VARCHAR2(1000),
                                        data       TIMESTAMP    NOT NULL,
                                        CONSTRAINT fk_historico_pet
                                            FOREIGN KEY (pet_id) REFERENCES yp_t_pets(id),
                                        CONSTRAINT ck_historico_tipo CHECK (tipo IN ('CONSULTA'))
);