-- ============================================================
-- V2 — Autenticação
-- ============================================================

CREATE TABLE yp_t_usuarios (
                               id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               email           VARCHAR2(150) NOT NULL,
                               senha_hash      VARCHAR2(255) NOT NULL,
                               perfil          VARCHAR2(20)  NOT NULL,
                               ativo           NUMBER(1) DEFAULT 1 NOT NULL,
                               criado_em       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                               responsavel_id  NUMBER(19),
                               veterinario_id  NUMBER(19),
                               CONSTRAINT uk_usuario_email UNIQUE (email),
                               CONSTRAINT uk_usuario_responsavel UNIQUE (responsavel_id),
                               CONSTRAINT uk_usuario_veterinario UNIQUE (veterinario_id),
                               CONSTRAINT ck_usuario_perfil
                                   CHECK (perfil IN ('RESPONSAVEL','VETERINARIO','ADMIN')),
                               CONSTRAINT ck_usuario_ativo
                                   CHECK (ativo IN (0,1)),
                               CONSTRAINT ck_usuario_vinculo
                                   CHECK (
                                       (perfil = 'RESPONSAVEL' AND responsavel_id IS NOT NULL AND veterinario_id IS NULL)
                                           OR (perfil = 'VETERINARIO' AND veterinario_id IS NOT NULL AND responsavel_id IS NULL)
                                           OR (perfil = 'ADMIN'       AND responsavel_id IS NULL     AND veterinario_id IS NULL)
                                       ),
                               CONSTRAINT fk_usuario_responsavel
                                   FOREIGN KEY (responsavel_id) REFERENCES yp_t_responsaveis(id),
                               CONSTRAINT fk_usuario_veterinario
                                   FOREIGN KEY (veterinario_id) REFERENCES yp_t_veterinarios(id)
);